//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//


delay 5000

LOAD_SUITE te_xmlomxclient

START_TESTCASE MM-IMAGE-OMX-FILESINK-001-HP
	START_TEST_BLOCK 30 te_xmlomxclient c:\omxil\tef\te_omx_filesink.ini
		CREATE_OBJECT OmxXmlTestWrapper InstanceName
		COMMAND	InstanceName New c:\omxil\tef\te_omx_filesink_image.xml
		COMMAND InstanceName RunTest BasicOperation
		COMMAND InstanceName RunTest GetFilenameNoFileSet_filesink
		COMMAND InstanceName RunTest GetFilenameOverFlow_filesink
		COMMAND InstanceName RunTest BasicOperation_nofilename_filesink
	END_TEST_BLOCK
END_TESTCASE MM-IMAGE-OMX-FILESINK-001-HP


